"""Increase code length

Revision ID: 8df02ad6f736
Revises: 5ba1dc374cf7
Create Date: 2025-07-30 09:56:19.630020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df02ad6f736'
down_revision = '5ba1dc374cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
